version: "3.8"

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh
    environment:
      SUPERSET_ADMIN_USERNAME: admin
      SUPERSET_ADMIN_PASSWORD: admin123
      SUPERSET_ADMIN_FIRST_NAME: Admin
      SUPERSET_ADMIN_LAST_NAME: User
      SUPERSET_ADMIN_EMAIL: admin@example.com
      DATABASE_URL: ${DATABASE_URL}  # Render Postgres URL from env
      SUPERSET_PORT: 8088
    ports:
      - "8088:8088"
    restart: unless-stopped